name: Compatibility

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  compatible:
    name: Go compatibility test
    strategy:
      matrix:
        version:
          - "1.12"
          - "1.13"
          - "1.14"
          - "1.15"
          - "1.16"
          - "1.17"
          - "1.18"
          - "1.19"
          - "1.20"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go ${{ matrix.version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.version }}

    - name: Build
      run: go build -v ./...

    - name: Unit test
      run: go test -v ./...

    - name: Coverage test
      run: go test -covermode=count -coverprofile=coverage.txt ./...
